services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=$PORT
        - WS_PORT=$WS_PORT
    container_name: fakepay-api
    restart: always
    env_file:
      - .env
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.fake-pay.rule=Host(`stage.sqwoz-hrov.ru`) && PathPrefix(`/payments`)'
      - 'traefik.http.routers.fake-pay.entrypoints=websecure'
      - 'traefik.http.routers.fake-pay.tls=true'
      - 'traefik.http.routers.fake-pay.tls.certresolver=myresolver'
      - 'traefik.http.services.fake-pay.loadbalancer.server.port=${PORT}'
      - 'traefik.http.middlewares.fake-pay-stripprefix.stripprefix.prefixes=/payments'
      - 'traefik.http.routers.fake-pay.middlewares=fake-pay-stripprefix@docker'
      - 'traefik.http.routers.wss.rule=Host(`stage.sqwoz-hrov.ru`) && PathPrefix(`/payments/ws`)'
      - 'traefik.tcp.services.wss.loadbalancer.server.port=${WS_PORT}'
      - 'traefik.http.routers.wss.entrypoints=websecure'
    expose:
      - '${PORT}:${PORT}'
      - '${WS_PORT}:${WS_PORT}'
    networks:
      - traefik
      - fakepay-db
    volumes:
      - ./public:/app/public
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  traefik:
    external: true
    name: $TRAEFIK_NETWORK
